<?php
// This file is part of Moodle - https://moodle.org/
//
// Moodle is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// Moodle is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with Moodle.  If not, see <https://www.gnu.org/licenses/>.

/**
 * Produces a sample tagged PDF using \core\pdf\document.
 *
 * The counterpart of pdflibtestpage.php, which does the same for the legacy TCPDF wrapper.
 *
 * @package    core
 * @copyright  2026 Moodle Pty Ltd.
 * @license    https://www.gnu.org/copyleft/gpl.html GNU GPL v3 or later
 */

use Com\Tecnick\Pdf\PdfConformance;

require(__DIR__ . '/../../../config.php');
require_once($CFG->libdir . '/filelib.php');

require_login();
$context = context_system::instance();
require_capability('moodle/site:config', $context);

$getpdf = optional_param('getpdf', 0, PARAM_INT);
$mode = optional_param('mode', 'pdfua1', PARAM_ALPHANUM);
$font = optional_param('font', '', PARAM_ALPHANUMEXT);

$conformance = PdfConformance::tryFrom($mode) ?? PdfConformance::Pdfua1;

if ($getpdf) {
    $doc = new \core\pdf\document(mode: $conformance);
    if ($font !== '') {
        $doc->set_default_font($font);
    }

    $doc->setTitle('Moodle tagged PDF library test');
    $doc->setSubject('Generated by lib/tests/other/pdfdocumenttestpage.php');
    $doc->setKeywords('Moodle, PDF, PDF/UA, tagged');
    $doc->setPDFFilename('pdfdocumenttestpage.pdf');

    $doc->addPage();
    $region = $doc->page->getRegion();

    // Every element below should end up as a structure element in the tagged output. Headings must
    // not skip a level, tables need their header cells marked up as such, and the image needs alt
    // text, otherwise the document cannot pass a PDF/UA check.
    $content = '<h1>Moodle tagged PDF library test</h1>';
    $content .= '<p>Generated by <b>\core\pdf\document</b> in <i>' . s($conformance->value) . '</i> mode.</p>';

    $content .= '<h2>Environment</h2>';
    $content .= '<table>';
    $content .= '<caption>Current settings</caption>';
    $content .= '<tr><th scope="col">Setting</th><th scope="col">Value</th></tr>';
    $rows = [
        'Moodle release' => $CFG->release,
        'Conformance mode' => $conformance->value,
        'K_PATH_CACHE' => defined('K_PATH_CACHE') ? constant('K_PATH_CACHE') : '(not defined)',
        'K_PATH_FONTS (TCPDF)' => defined('K_PATH_FONTS') ? constant('K_PATH_FONTS') : '(not defined)',
    ];
    foreach ($rows as $name => $value) {
        $content .= '<tr><td>' . s($name) . '</td><td>' . s((string) $value) . '</td></tr>';
    }
    $content .= '</table>';

    $content .= '<h2>Font directories searched</h2><ul>';
    foreach (\core\pdf\document::get_font_directories() as $dir) {
        $content .= '<li>' . s($dir) . '</li>';
    }
    $content .= '</ul>';

    $content .= '<h2>Text samples</h2>';
    $content .= '<p>Latin: The quick brown fox jumps over the lazy dog.</p>';
    $content .= '<p>Accented: r&eacute;sum&eacute;, na&iuml;ve, Stra&szlig;e, &ccedil;a va.</p>';
    $content .= '<blockquote>A block quote, which should be tagged as BlockQuote.</blockquote>';
    $content .= '<p>A <a href="' . $CFG->wwwroot . '">link to this site</a>, tagged as Link.</p>';

    $content .= '<h2>Image with alternative text</h2>';
    $content .= '<figure>';
    $content .= '<img src="' . $CFG->dirroot . '/pix/moodlelogo.png" alt="The Moodle logo" width="120" />';
    $content .= '<figcaption>The Moodle logo, tagged as Figure with a Caption.</figcaption>';
    $content .= '</figure>';

    $doc->addHTMLCell(
        width: $region['RW'] - 40,
        height: 0,
        posx: 20,
        posy: 20,
        html: $content,
    );

    send_file($doc->getOutPDFString(), 'pdfdocumenttestpage.pdf', 0, 0, true, true, 'application/pdf');
    exit();
}

$PAGE->set_url('/lib/tests/other/pdfdocumenttestpage.php');
$PAGE->set_context($context);
$PAGE->set_title('Tagged PDF library test');
$PAGE->set_heading('Tagged PDF library test');

echo $OUTPUT->header();
echo $OUTPUT->heading('Generate a test PDF', 2);
echo html_writer::tag('p', 'Generates a sample document with headings, a table, a list, a link and an '
    . 'image with alternative text, so that the structure of the output can be inspected.');
echo html_writer::start_tag('ul');
$modes = [
    'pdfua1' => 'Tagged, PDF/UA-1. This is what \core\pdf\document produces by default.',
    '' => 'Untagged. A baseline for comparison only, not a mode anything should be generating: '
        . 'useful for seeing what the structure tree adds, and what it costs in file size.',
];
foreach ($modes as $value => $label) {
    $url = new moodle_url($PAGE->url, ['getpdf' => 1, 'mode' => $value]);
    echo html_writer::tag('li', html_writer::link($url, $label));
}
echo html_writer::end_tag('ul');
echo $OUTPUT->footer();
